import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { IGeneralLayoutProps } from "@/types/app/layout-props/GeneralLayoutProps";
import AppProviders from "@/providers";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

/**
 * Top-level application layout that wraps pages with global providers, font variables, and a global toaster.
 *
 * @param children - The page content to render inside the layout's body.
 * @returns The root React element containing an `<html>` and `<body>` with configured font classes, wrapped by app providers and including a global toaster.
 */
export default function RootLayout({
	children,
}: Readonly<IGeneralLayoutProps>) {
	return (
		<AppProviders>
			<html lang="en">
				<body
					className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				>
					{children}
					<Toaster />
				</body>
			</html>
		</AppProviders>
	);
}